name = "LinearRegressionInputUncetainty"
uuid = "c977da63-dc55-4e90-9e9d-5cb77bb2d17a"
authors = ["Nikos Gianniotis"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
